version: '2.1'
services:
  db:
    image: postgres:9-alpine
    container_name: giskis-db
    environment:
      - POSTGRES_PASSWORD=postgres

  giskis:
    image: rainu/giskis
    container_name: giskis
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - SCAN_DIR=/in
      - OUTPUT_DIR=/out
      - MIN_FLMT=10000
    volumes:
      - ./in:/in
      - ./out:/out
    depends_on:
      - db
