version: '2.1'
services:
  db:
    image: mongo
    container_name: giskis-db

  giskis:
    image: rainu/giskis
    container_name: giskis
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://db:27017/test
      - SCAN_DIR=/in
      - OUTPUT_DIR=/out
      - MIN_FLMT=10000
    volumes:
      - ./in:/in
      - ./out:/out
    depends_on:
      - db
